### ISSUE TITLE
Showing "\002a" for "\\*"

### ISSUE THREAD

**Issue by shahnewaz469** [DavidLari/Haring#3]
Hello,
I've found an issue when I switched from "MarkdownKit".
"\002a" is showing instead of "\\*".
This issue is caused by this line:
`guard count > 4 else { return nil }`
in String extension class `func unescapeUTF16() -> String?`
Is this necessary or can just remove the `guard`?
Would please take care of this?

Thanks

**Comment by DavidLari** [comment]
I wonder if it should be ```guard count >= 4 else { return nil }```, greater than or equal to.

**Comment by shahnewaz469** [comment]
I've tested this if I ignore this line it is as expected as markdown kit, even Markdown kit doesn't have the `guard`.

**Comment by DavidLari** [comment]
Yes, someone created a pull request to MarkdownKit to add the guard statement, but the author never merged it. I took most of the pull requests from MarkdownKit and applied them to Haring. This was to fix a potential crash with malformed escape codes. Can you test with the ```>=``` and see if that works? If so, then I will make the correction to the repository and push a new version to pods.

**Comment by shahnewaz469** [comment]
Yeah, it's working for `>=`.
So, would you please update the version with this?
Then I can use this library.

Thanks

**Comment by DavidLari** [comment]
I have just pushed version 2.0.6 to cocoapods with the fix. Thanks for submitting this issue! :)
