### ISSUE TITLE
Is there a way to convert NSAttributedString back to markdown?

### ISSUE THREAD

**Issue by hyouuu** [DavidLari/Haring#9]
Is there a way in Haring to do that? If not, any recommended approaches? Sorry if it's a dumb question

**Comment by DavidLari** [comment]
I have never seen such a library and it would seem like a daunting task to create one.

**Comment by hyouuu** [comment]
Thanks for the quick reply! So if I want a user editable UITextView without showing the marks (like the Notes app), then I'd have to keep 2 copies in sync? So whenever user enters a char, find the corresponding position in the markdown version and add it? That seems hard to do too and inefficient :/ Any thoughts?
